<center style="margin-top: 100px">
<?php $this->flash->output();?>
<h2>文章发布</h2><a href="../test/show">列表</a>
<?php echo $this->tag->form("../store/test/commentDo"); ?>
    <table>
    <tr>
        <td>文章标题</td>
        <td><input type="text" style="width:300px;" name="title"></td>
    </tr>
    <tr>
        <td>文章内容</td>
        <td><textarea style="width:300px;height:100px;" name="com"></textarea></td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("提交") ?></td>
    </tr>
    </table>
</center>
