<center style="margin-top: 100px">
<?php $this->flash->output();?>
<h2>文章发布</h2><a href="../test/show">返回</a>
<?php echo $this->tag->form("../store/test/commentDo"); ?>
    <table>
    <tr>
        <td>文章标题</td>
        <td><input type="text" style="width:300px;" value="<?php echo $data[0]['title']; ?>" name="title"></td>
    </tr>
        <input type="hidden" name="id" value="<?php echo $data[0]['id']; ?>">
    <tr>
        <td>文章内容</td>
        <td><textarea style="width:300px;height:100px;" name="com" ><?php echo $data[0]['com']; ?></textarea></td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("修改") ?></td>
    </tr>
    </table>
</center>
